import { Router } from "express";
import { adminController } from "../controllers/adminController.js";
import { authenticate } from "../middleware/authenticate.js";
import { requireAdmin } from "../middleware/requireAdmin.js";

const router = Router();

router.get(
  "/admin/stats",
  authenticate,
  requireAdmin,
  adminController.getStats,
);
router.get(
  "/admin/users",
  authenticate,
  requireAdmin,
  adminController.getUsers,
);
router.patch(
  "/admin/users/:id/block",
  authenticate,
  requireAdmin,
  adminController.blockUser,
);
router.patch(
  "/admin/users/:id/unblock",
  authenticate,
  requireAdmin,
  adminController.unblockUser,
);
router.get(
  "/admin/tutors/pending",
  authenticate,
  requireAdmin,
  adminController.getPendingTutors,
);
router.patch(
  "/admin/tutors/:id/verify",
  authenticate,
  requireAdmin,
  adminController.approveTutor,
);
router.patch(
  "/admin/tutors/:id/reject",
  authenticate,
  requireAdmin,
  adminController.rejectTutor,
);
router.patch(
  "/admin/tutors/:id/interview",
  authenticate,
  requireAdmin,
  adminController.scheduleInterview,
);
router.get(
  "/admin/students/pending",
  authenticate,
  requireAdmin,
  adminController.getPendingStudents,
);
router.patch(
  "/admin/students/:id/verify",
  authenticate,
  requireAdmin,
  adminController.approveStudent,
);
router.patch(
  "/admin/students/:id/reject",
  authenticate,
  requireAdmin,
  adminController.rejectStudent,
);

router.get(
  "/admin/requests",
  authenticate,
  requireAdmin,
  adminController.getAllRequests,
);
router.patch(
  "/admin/requests/:id/accept",
  authenticate,
  requireAdmin,
  adminController.acceptRequest,
);
router.patch(
  "/admin/requests/:id/reject",
  authenticate,
  requireAdmin,
  adminController.rejectRequest,
);
router.delete(
  "/admin/requests/:id",
  authenticate,
  requireAdmin,
  adminController.deleteRequest,
);

router.get(
  "/admin/courses",
  authenticate,
  requireAdmin,
  adminController.getCourses,
);
router.post(
  "/admin/courses",
  authenticate,
  requireAdmin,
  adminController.createCourse,
);
router.patch(
  "/admin/courses/:id",
  authenticate,
  requireAdmin,
  adminController.updateCourse,
);
router.delete(
  "/admin/courses/:id",
  authenticate,
  requireAdmin,
  adminController.deleteCourse,
);

export default router;
